language: node_js
node_js:
  - 10
  - 8
  - 6
  - node
branch:
  only:
  - master
cache: npm
script:
- npm run lint
- npm test
- npm run coveralls
deploy:
  provider: npm
  email: h.nsr69@gmail.com
  api_key: ${NPM_TOKEN}
  on:
    tags: true
